//
// Created by klewy on 8/14/26.
//

#ifndef WAIWAIDPI_CONSTS_HPP
#define WAIWAIDPI_CONSTS_HPP

constexpr auto DEFAULT_CONNECTION_TIMEOUT_SECS = 60;
constexpr auto SYN_TCP_CONNECTION_TIMEOUT_SECS = 15;
constexpr auto ESTAB_TCP_CONNECTION_TIMEOUT_SECS = 6000;
constexpr auto FIN_TCP_CONNECTION_TIMEOUT_SECS = 15;
constexpr auto CLOSE_TCP_CONNECTION_TIMEOUT_SECS = 0;

constexpr auto CHECK_DEAD_CONNECTIONS_INTERVAL_SECS = 10;
constexpr auto HTTP_PARSE_LIMIT = 8000;

#endif// WAIWAIDPI_CONSTS_HPP
